name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:

    - name: Checkout
      uses: actions/checkout@v2


    - name: Build and Push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: rahuketu86/fastpages-emacs
        tag_with_ref: true
    
#     - name: Run local registry
#       run: docker run -d -p 5000:5000 registry:2
    
#     - name: Build and push image
#       uses: ./
#       env:
#         DOCKER_BUILDKIT: 1
#       with:
#         registry: localhost:5000
#         repository: temp/workflow
#         tags: foo
      
#     - name: Remove local image
#       run: docker image rm localhost:5000/temp/workflow:foo

#     - name: Run image from registry
#       run: docker run localhost:5000/temp/workflow:foo
# © 2020 GitHub, Inc.