#+OPTIONS: toc:nil 
#+BEGIN_EXPORT html
---
layout: post
categories: [orgmode]
title: Emacs Conifguration is fixed
---
<link rel="stylesheet" type="text/css" href="https://gongzhitaao.org/orgcss/org.css"/>
#+END_EXPORT

#+TOC: headlines 3

This post contains sample configuration for my emacs in an org file

* Emacs init.el
  #+BEGIN_EXAMPLE
    (package-initialize)

    (require 'org)
    (org-babel-load-file
          (expand-file-name "configuration.org"
                             user-emacs-directory))
  #+END_EXAMPLE

* Emacs Customization Group
  #+BEGIN_SRC emacs-lisp
    (setq custom-file
          (expand-file-name "custom.el"
                            user-emacs-directory))
  #+END_SRC

* Emacs Repositories
  #+BEGIN_SRC emacs-lisp
    (require 'package)
    ;;;(add-to-list 'package-archives
    ;;;'             '("marmalade" . "http://marmalade-repo.org/packages/") t)
    (add-to-list 'package-archives
                 '("melpa-stable" . "https://stable.melpa.org/packages/") t)
    (add-to-list 'package-archives
                 '("melpa" . "http://melpa.org/packages/")
                 t)

	(add-to-list 'package-archives 
	             '("org" . "http://orgmode.org/elpa/")
				 t)
    (when (< emacs-major-version 24)
      ;; For important compatibility libraries like cl-lib
      (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
    (package-initialize)

  #+END_SRC


* Utility Functions
** Function to open this configuration file
   #+BEGIN_SRC emacs-lisp

     (defvar config-file-name "configuration.org")

     (defun my-config()
       "Function to open org configuration file"
       (interactive)
  
       (find-file (expand-file-name config-file-name
                                    user-emacs-directory)))  
   #+END_SRC

* Splash Screen and bars
  #+BEGIN_SRC emacs-lisp
    (setq inhibit-splash-screen t
	  ;;      initial-scratch-message nil
	  ;;    initial-major-mode 'org-mode
	  )

    (scroll-bar-mode -1)
    (tool-bar-mode -1)
    ;; (menu-bar-mode -1)
  #+END_SRC

* Configure Emacs for use-package
  #+BEGIN_SRC emacs-lisp
     (unless (package-installed-p 'use-package)
     (package-refresh-contents)
     (package-install 'use-package))
    ;;  (setq use-package-verbose t)
    ;;  (setq use-package-always-ensure t)
     ;; (eval-when-compile
     ;; (require 'use-package))
     ;; (use-package auto-compile
     ;; :config (auto-compile-on-load-mode))
     ;; (require 'diminish)
    ;;  ;;
    (require 'bind-key)
   #+END_SRC


* Emacs Custom Theme
  #+BEGIN_SRC emacs-lisp
    (use-package monokai-theme
      :ensure t
      :init (load-theme 'monokai t))
  #+END_SRC

* Setup Ido and smex
  #+BEGIN_SRC emacs-lisp
    ;; Activate ido
    (require 'ido)
    (ido-mode t)

    ;; Set up smex
    (use-package smex
      :ensure t
      :bind (("M-x" . smex))
      :config (smex-initialize))
  #+END_SRC
* Setup Guru Mode
  Guru mode works by disabling common key bindings and pushing for
  Emacs standard key bindings. Instead of global hook up Textmode and
  other so that it plays nice with ido-mode.
  #+BEGIN_SRC emacs-lisp
    (use-package guru-mode
      :ensure t
      :init
      (setq-default major-mode 'text-mode)
      :config
      (add-hook 'prog-mode-hook 'guru-mode)
      (add-hook 'text-mode-hook 'guru-mode)
     )
  #+END_SRC
* Setup Magit
  Magit is a git porcelain. With this we can stay within emacs for
  configuration modifications and commiting to git.
  #+BEGIN_SRC emacs-lisp
    (use-package magit
      :ensure t
      :bind ("C-x g" . magit-status))
  #+END_SRC
  
* Setup Company Mode
  Company mode is used for autocompletion in Emacs.
  #+BEGIN_SRC emacs-lisp
    (use-package company
      :ensure t
      :defer t
      :config
       (global-company-mode)

;;      :config
;;       (global-company-mode))
	   )
  #+END_SRC
* Org-Mode Settings
  Global settings for all the org-mode buffers.

  #+BEGIN_SRC emacs-lisp
    (use-package org-mode
      :init (remove-hook 'org-mode-hook 'guru-mode)
      :bind (("\C-cl" . org-store-link)
             ("\C-ca" . org-agenda)
             ("\C-cc" . org-capture)
             ("\C-cb" . org-iswitch))
      :config
       (remove-hook 'org-mode-hook 'guru-mode))
  #+END_SRC

  Additional Org Mode plugins
  - Org Mode with Twitter bootstrap(ox-twbs)
    #+BEGIN_SRC emacs-lisp
      (use-package ox-twbs
        :ensure t
        :defer t)
    #+END_SRC

* Blog Settings

  #+BEGIN_SRC emacs-lisp
    (use-package htmlize
     :ensure t)
  #+END_SRC

* Setup ox-reveal
 #+BEGIN_SRC emacs-lisp
    (use-package org-re-reveal
      :ensure t
      :init
    )
    (package-refresh-contents)
   (use-package reftex
                :ensure t
                :commands turn-on-reftex
                )
     (use-package org-ref
         :ensure t
         :after org)

      (use-package org-re-reveal-ref
         :ensure t
         :after org)

  #+END_SRC

* Setup htmlize and addtional org-contrib
 #+BEGIN_SRC emacs-lisp
  (dolist (pkg '(org-plus-contrib htmlize))
    (unless (package-installed-p pkg)
      (package-install pkg)))
  #+END_SRC


* FastPages link 

The idea is simple 

- Links are prepended by a directive
- When doing html export link get converted into jekyll include statement already defined in the code
- When exporting to other backends it follows the same structure as normal link for that structure

#+begin_src emacs-lisp :results silent
  (defun jekyll-include (inc-tmpl url)
    (s-lex-format "{% include ${inc-tmpl} content='<a href=\"${url}\">${url}</a>' %}"))
       
  (org-link-set-parameters
   "yt"
   :export (lambda (path desc backend)
	     (cond
	      ((eq 'html backend)
	       (jekyll-include "youtube.html" path ))))
   :help-echo "This links helps in exporting link to jekyll youtube liquid template")

#+end_src

